### ISSUE TITLE
Program exception

### ISSUE THREAD

**Issue by novice55** [CodingWonders/DISMTools#208]
.
  After installing DISMTools and completing the mounting of the first image, 
all buttons in the servicing session window remain inactive (grayed out) <img_1>, except for the "Mount Image" button. 
To activate all buttons, you have to exit the Maintenance Session by clicking on Unload project and reload the project 
from the "Recent projects" list in the main window.

  Next, when you click on the "Get app information.." button, the corresponding window opens, but the list area 
(on the left) remains empty and nothing else happens <img_2>. 

  When clicking on the following buttons: 
 - "Get package information..",
 - "Get future information..",
 - "Get capability information..",
 - "Get driver information.."
an exception appears, and when closing the window with the exception, the program crashes. 

  I tried to use DISMTools to service the following original Windows images:
 - Windows 11 24H2 26100.2605
 - Windows 10 22H2 19045.5247
 - Windows 10 22H2 19045.2965
 - Windows 10 21H1 19043.1200
 I ran the program both on the host and on the virtual machine, and also used different versions of DISMTools 
 (0.5.1, 0.6pre and 0.6) - the result is the same.
------------------------------------------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   в DISMTools.GetPkgInfoDlg.GetPkgInfoDlg_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.6.0.24122
 - Preview release? No
 - Branch: stable
 - Build time: 241220-1044
 - Portable copy? Yes

Information about the image loaded in this project:
 - Image name: Windows 10 Pro
 - Image description: Windows 10 Pro
 - Image version: 10.0.19045.5247
Machine information:
 - Computer manufacturer: Micro-Star International Co., Ltd.
 - Computer model: MS-7C56
 - BIOS name/description: A.I0 A.I0
 - System Management BIOS (SMBIOS) version: A.I0

Operating system information:
 - OS name: Microsoft Windows 10 Pro
 - OS version: 10.0.19043.1200
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: AMD Ryzen 5 5600 6-Core Processor              
 - Processor caption: AMD64 Family 25 Model 33 Stepping 2
 - Processor manufacturer: AuthenticAMD
 - Processor family (WMI type): 107
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

![img_1](https://github.com/user-attachments/assets/824846db-0cff-4e6f-8660-78202cce8a67)
![img_2](https://github.com/user-attachments/assets/163edf63-b9b2-4671-a877-74ac3b308274)

**Comment by CodingWonders** [comment]
This is a known issue that I'm still investigating. Background processes sometimes don't fire up when they are supposed to.

I hope that with all the changes I'm making to the logging infrastructure I can locate the actual cause of the issue

**Comment by CodingWonders** [comment]
@novice55, it seems that the issue is now fixed. Could you try the latest nightly installers of the "dt_pre_2511" branch?

Here's a direct link to it: https://github.com/CodingWonders/dt-nightly-installers/raw/refs/heads/main/dt_pre_2511/dt_setup.exe

**Comment by CrPO4** [comment]
Not the issue starter but had a similar issue with newest Windows 11 24H2 image on release version.
This pre-release one gets the job done, at least for me.
Thank you for what you're doing for the community.

**Comment by vinicentus** [comment]
I still have this issue. The whole "Internal Error"-window also freezes, and I have to use Task Manager to close the program.
Before the freeze, it copies the following info to the clipboard:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DISMTools.MainForm.ImgBW_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

Error Message: Object reference not set to an instance of an object.

Error Code (HRESULT): 80004003

Program information:
 - DISMTools Version: 0.6.1.25032
 - Preview release? No
 - Branch: stable
 - Build time: 250321-1203
 - Portable copy? No

Information about the image loaded in this project:
 - Image name: imgName
 - Image description: imgDesc
 - Image version: imgVersion
Machine information:
 - Computer manufacturer: LENOVO
 - Computer model: 82JU
 - BIOS name/description: GKCN65WW GKCN65WW
 - System Management BIOS (SMBIOS) version: GKCN65WW

Operating system information:
 - OS name: Microsoft Windows 11 Home
 - OS version: 10.0.22631.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: AMD Ryzen 7 5800H with Radeon Graphics         
 - Processor caption: AMD64 Family 25 Model 80 Stepping 0
 - Processor manufacturer: AuthenticAMD
 - Processor family (WMI type): 107
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.
```

![Image](https://github.com/user-attachments/assets/ccd7c8ee-e2e0-475d-adb4-3dfc17adae58)
